using ScreenStudio.Core.Cursor;
using ScreenStudio.Core.Math;
using SysMath = System.Math;

namespace ScreenStudio.Core.Zoom;

/// <summary>Auto vs manual zoom source (deliverable: "Auto vs manual zoom modes").</summary>
public enum ZoomMode
{
    /// <summary>Keyframes are generated by the detector from cursor activity.</summary>
    Automatic,
    /// <summary>Keyframes are authored by the user in the timeline editor.</summary>
    Manual,
}

/// <summary>Configuration for automatic zoom detection. Tunable so the editor can
/// dial sensitivity without changing the algorithm.</summary>
public sealed class ZoomDetectionOptions
{
    /// <summary>Zoom scale applied when an interesting action is detected (e.g. 2.0 = 2x).</summary>
    public double ZoomScale { get; set; } = 2.0;
    /// <summary>How long (ms) the zoom holds at peak before easing back out.</summary>
    public double HoldMs { get; set; } = 600.0;
    /// <summary>Cursor speed (px/ms) below which the cursor is considered "paused".</summary>
    public double PauseSpeedThreshold { get; set; } = 0.05;
    /// <summary>Minimum pause duration (ms) to count as a zoom-worthy pause.</summary>
    public double PauseMinMs { get; set; } = 350.0;
    /// <summary>Minimum gap (ms) between two generated keyframes (avoids jittery zoom spam).</summary>
    public double MinKeyframeGapMs { get; set; } = 250.0;
}

/// <summary>Task 004 — automatic cursor zoom detection.
/// Analyzes a cursor stream and emits a ZoomProgram of keyframes at "interesting" moments:
/// clicks, drags, and pauses. Produces paired zoom-in / zoom-out keyframes with holds so
/// the camera eases in, holds on the action, then eases back out.</summary>
public sealed class ZoomDetector
{
    public ZoomMode Mode { get; set; } = ZoomMode.Automatic;
    public ZoomDetectionOptions Options { get; set; } = new();

    /// <summary>Scan the cursor stream and produce a zoom program.
    /// raw must be sorted ascending by TimestampMs.</summary>
    public ZoomProgram Detect(IReadOnlyList<CursorEvent> raw, Vec2 sourceSize)
    {
        var program = new ZoomProgram();
        if (raw.Count == 0) return program;

        // Start at default (no zoom, centered).
        program.Add(ZoomKeyframe.Default(raw[0].TimestampMs));

        // The gap gate measures distance from the last zoom EVENT, not the baseline seed,
        // so the first real action always qualifies regardless of how soon it follows t=0.
        double lastKeyMs = double.NegativeInfinity;

        for (int i = 1; i < raw.Count; i++)
        {
            var prev = raw[i - 1];
            var cur = raw[i];
            var dt = cur.TimestampMs - prev.TimestampMs;
            if (dt <= 0) continue;

            var speed = (cur.Position - prev.Position).Length / dt;
            var isClick = cur.IsClick;
            var isPause = speed < Options.PauseSpeedThreshold && dt >= Options.PauseMinMs;

            if ((isClick || isPause) && (cur.TimestampMs - lastKeyMs) >= Options.MinKeyframeGapMs)
            {
                var rel = RelativeTo(cur.Position, sourceSize);
                // Zoom IN to the action.
                program.Add(new ZoomKeyframe(cur.TimestampMs, rel, Options.ZoomScale));
                // Hold, then zoom back OUT.
                program.Add(new ZoomKeyframe(cur.TimestampMs + Options.HoldMs, rel, Options.ZoomScale));
                program.Add(ZoomKeyframe.Default(cur.TimestampMs + Options.HoldMs + Options.HoldMs));
                lastKeyMs = cur.TimestampMs + Options.HoldMs;
            }
        }

        return program;
    }

    private static Vec2 RelativeTo(Vec2 abs, Vec2 size)
        => size.X > 0 && size.Y > 0
            ? new(abs.X / size.X, abs.Y / size.Y)
            : new(0.5, 0.5);
}
